### PR TITLE
Add Picket to Ecosystem

### PR DESCRIPTION
**Pull request by devstein**

### CODE REVIEW

**Comment by pi0neerpat** [comment]
I'm thinking maybe this isn't the best category for this type of tool.

**Comment by devstein** [comment]
> I'm thinking maybe this isn't the best category for this type of tool.

What category makes sense? I put it in frontend because it's primarily a client-side library

**Comment by pi0neerpat** [comment]
The tools here are mostly for building dapps, where Pickett is more of standalone service. I'd recommend moving it into the ecosystem doc instead

**Comment by devstein** [comment]
@pi0neerpat Makes sense. Just moved it. Let me know what you think.

**Comment by pi0neerpat** [comment]
Awesome thanks!

**Pull request merged**
