### PR TITLE
Added Web3Client

### PR DESCRIPTION
**Pull request by poriyaalarsamvelraja**
Added web3client in IDEs list.

Kindly, feel free to comment or reject my PR if it is not standard to the repo.

### CODE REVIEW

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
Hey this is awesome! Nice work. I'm the creator of oneclickdapp and I love to see new ideas and features for contract interaction tooling.

I think this fits better under the category `#### Ethereum ABI (Application Binary Interface) tools`

**Comment by poriyaalarsamvelraja** [comment]
Hi @pi0neerpat 

Thanks for the suggestion. Moved it under ethereum abi tools as requested. 

Between great idea from your side happy building product. 🫡

**Comment by poriyaalarsamvelraja** [comment]
Hi @pointtoken  Can you approve it?

**Comment by poriyaalarsamvelraja** [comment]
Hi

A friendly nudge to review and merge this

**Comment by pi0neerpat** [comment]
Thank you!

**Pull request merged**
