### PR TITLE
Add Etherspot SDK

### PR DESCRIPTION
**Pull request by arddluma**
Etherspot SDK is an open-source Smart Wallet MultiChain SDK which supports most of the EVM-compatible chains
Web: https://etherspot.io/
GitHub: https://github.com/etherspot/etherspot-sdk

### CODE REVIEW

**Comment by pi0neerpat** [comment]
Looks neat. Is this live yet? I see theres a closed waitlist

**Comment by arddluma** [comment]
> Looks neat. Is this live yet? I see theres a closed waitlist

Hey @pi0neerpat,
Yeah it is live 🚀, the private waitlist is for investments opportunities. 
https://github.com/pillarwallet/pillarwallet and https://airdropme.io are powered by Etherspot SDK.
Feel free to check [Docs](https://docs.etherspot.dev/) and [Playground](https://try.etherspot.dev/).
Thanks !

**Comment by pi0neerpat** [comment]
LIT You better believe I'll check this out soon. Getting people wallets faster is what I'm all about. Can we connect on twitter? I'm @pi0neerpat there

**Comment by arddluma** [comment]
> LIT You better believe I'll check this out soon. Getting people wallets faster is what I'm all about. Can we connect on twitter? I'm @pi0neerpat there
Hey man 👋,
Glad to hear that! I've already DM'd you in tw :)
See ya there!
Thanks

**Pull request merged**
