### PR TITLE
Add Torus SDK to build Dapps with a seamless UX

### PR DESCRIPTION
**Pull request by YZhenY**
Hi!

Big fan of this list, its rare to find something so comprehensive. Would love to add Torus to the list, we help apps have a seamless UX utilizing dkgs for key management

### CODE REVIEW

**Comment by YZhenY** [comment]
@sot528 let me know anything i can do to get this merged!

**Comment by pi0neerpat** [comment]
Looks awesome. 

One thing though- Portis, Fortmatic and Torus do not belong in the `New developers start here` category. Would you mind removing them before we merge?

**Comment by YZhenY** [comment]
@pi0neerpat done, perhaps torus can stay though? =)

**Comment by pi0neerpat** [comment]
Yeah, I'm not totally sure where these should go. But I do agree they should be listed on the main readme, and not exiled to the ecosystems page.

Maybe they can all go here? https://github.com/ConsenSys/ethereum-developer-tools-list#frontend-ethereum-apis

**Comment by YZhenY** [comment]
made the changes @pi0neerpat

**Comment by pi0neerpat** [comment]
Coo beans

**Pull request merged**
