### PR TITLE
Add aleph.im

### PR DESCRIPTION
**Pull request by adrien-be**
Aleph.im is a unique blend of onchain and offchain decentralized technologies. Compatible with Ethereum of course.

### CODE REVIEW

**Comment by pi0neerpat** [comment]
Can you actually move "stow" under the `Secure Decentralized Data Protocols` heading down to the new one you made? ty!

**Comment by adrien-be** [comment]
Yep. Done

**Comment by pi0neerpat** [comment]
Sorry if I wasn't clear. I actually like your heading better `Decentralized Cloud (Database, File Storage and Computing)`

If you want to continue to use it we can, otherwise I can merge it the way it is now

**Comment by adrien-be** [comment]
No problem. That's it. Done :)

**Comment by pi0neerpat** [comment]
Thanks for your contribution!

**Pull request merged**
