### PR TITLE
Add secret_tech projects

### PR DESCRIPTION
**Pull request by hlogeon**
Added free & open source web wallet for ETH and ERC-20 tokens:
https://moonwallet.tech
https://github.com/secret-tech/backend-token-wallets
https://github.com/secret-tech/frontend-moon-wallet

Added free & open source ICO dashboard by secret_tech
https://icodashboard.space
https://github.com/secret-tech/backend-ico-dashboard
https://github.com/secret-tech/frontend-ico-dashboard

### CODE REVIEW

**Comment by pakaplace** [comment]
FYI, Wallets will likely be moved to a new section with DApps and etc.  Has your ICO dashboard been used in production? I think it should probably also fall under the DApps section.

**Comment by hlogeon** [comment]
@pakaplace 
> Has your ICO dashboard been used in production?

Yes. It has been used for Jincor ICO, Starflow ICO, Quantor ICO and other projects. Some of that projects are still live. We also have security audit report by the 3rd party company but unfortunatly its in Russian

**Comment by pi0neerpat** [comment]
@hlogeon I just added a dapps category for you!

**Comment by pi0neerpat** [comment]
Doh! it looks like dapps actually belong here https://github.com/ConsenSys/ethereum-developer-tools-list/blob/master/EcosystemResources.md. Sorry for the confusion.

**Comment by pi0neerpat** [comment]
Closing for now. Please re-open if you wish to continue

**Pull request closed without merging**
