### PR TITLE
Add GhostGraph: create EVM chain indexers using Solidity

### PR DESCRIPTION
**Pull request by chrischang**
Add GhostGraph: create EVM chain indexers using Solidity

**Website:** https://ghostgraph.xyz
**Docs:** https://docs.ghostlogs.xyz/ghostgraph/overview/

### CODE REVIEW

**Comment by chrischang** [comment]
@Maxservais would you mind looking at this PR?

**Comment by pi0neerpat** [comment]
If you want to create a whole new category that's fine, but you should compile all the existing indexer tools (there are several) in order to make it clear.

Alternatively you should place the item in the list with the other indexers.

**Comment by chrischang** [comment]
> If you want to create a whole new category that's fine, but you should compile all the existing indexer tools (there are several) in order to make it clear.
> 
> Alternatively you should place the item in the list with the other indexers.

@pi0neerpat Thanks for the suggestion. I chose the second option so that I wouldn't redo what the other contributors did.

Cheers!

**Comment by Maxservais** [comment]
> @Maxservais would you mind looking at this PR?

Hey! I am not one of the Reviewers on this repo so can't really merge your PR unfortunately

**Comment by chrischang** [comment]
> > @Maxservais would you mind looking at this PR?
> 
> Hey! I am not one of the Reviewers on this repo so can't really merge your PR unfortunately

Understood. Thanks for the quick response!

**Comment by chrischang** [comment]
gm, @pi0neerpat could you review this?

**Comment by pi0neerpat** [comment]
thank you!

**Pull request merged**
