### PR TITLE
Update README.md - adding useWeb3

### PR DESCRIPTION
**Pull request by wslyvh**
Adding useWeb3.xyz - A curated overview of the best and latest resources on Ethereum, blockchain and Web3 development.

This repo is also linked on there :) 
https://www.useweb3.xyz/websites

### CODE REVIEW

**Review by moodmosaic — APPROVED** [review]
👍

**Comment by pi0neerpat** [comment]
Nice this is so cool!

**Comment by wslyvh** [comment]
Thank you! 🙌

**Comment by krambler** [comment]
This is great! Really good job! ;)

**Pull request merged**
