### PR TITLE
Added Diamond Standard

### PR DESCRIPTION
**Pull request by mudgen**
Adds the Diamond Standard as one of the contract patterns.

### CODE REVIEW

**Comment by pi0neerpat** [comment]
Hey would you mind adding a description too? Also, would you prefer this goes in the Upgradeability section?

**Comment by mudgen** [comment]
Hey, great, I think it should go in contract patterns.  Yes, I'll add a description.

**Comment by mudgen** [comment]
I just added a description.

**Comment by pi0neerpat** [comment]
Noice!

**Comment by mudgen** [comment]
I created a new pull request to update the link to EIP-2535 Diamond Standard and improve the description a little more.

Thanks for keeping this documentation up to date!

**Pull request merged**
