### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mdcoon**
Added a new entry under monitoring section.

### CODE REVIEW

**Comment by mdcoon** [comment]
Beta access? The site is live right now. There is a Live Demo button that will take you to the actual dashboard for a popular contract (CryptoKitties). We've gotten feedback that the landing page makes it seem like it's not actually real so we need to address this.
This is a free platform right now and we will likely offer premium services to dApp dev teams in the near future.
It is totally usable today.
Mike
    On Friday, October 26, 2018, 7:23:28 AM EDT, Parker Place <notifications@github.com> wrote:  
 
 
Very cool, I just requested beta access. Before I merge, I'd like some info on pricing (free vs paid) as well as when it'll actually be available. I've tried to limit this list to tools that developers can use today.

**Comment by mdcoon** [comment]
Oh I see, you requested early access to one of the upcoming features. Those are just additional things we'll offer dev teams. 
As an analytics platform, however, the site is available now. Anyone can search for a contract by its address and see its metrics. 
We are going to change the landing page to reflect more global dApp information so that it's easier to drill down into the details or just be able to see dApps according to different criteria (least expensive, week-over-week user growth, volume, etc).
    On Friday, October 26, 2018, 7:31:30 AM EDT, Michael D. Coon <mdcoon1@yahoo.com> wrote:  
 
  Beta access? The site is live right now. There is a Live Demo button that will take you to the actual dashboard for a popular contract (CryptoKitties). We've gotten feedback that the landing page makes it seem like it's not actually real so we need to address this.
This is a free platform right now and we will likely offer premium services to dApp dev teams in the near future.
It is totally usable today.
Mike
    On Friday, October 26, 2018, 7:23:28 AM EDT, Parker Place <notifications@github.com> wrote:  
 
 
Very cool, I just requested beta access. Before I merge, I'd like some info on pricing (free vs paid) as well as when it'll actually be available. I've tried to limit this list to tools that developers can use today.

**Comment by pi0neerpat** [comment]
Howdy @mdcoon . Is this project still live? Maybe we need to add DappHub instean?

**Comment by pi0neerpat** [comment]
Closing for now. Please re-open if you wish to continue

**Pull request closed without merging**
